Repository Ridderrasmus/RPVoiceChat, pull requests merged in 2023-10, with the labels that each got.

#85 Fix the crash caused by the new update
  App.config
  RPVoiceChat.csproj
Labels: bug

#82 Add i18n for code part of the mod
  assets/rpvoicechat/lang/en.json
  assets/rpvoicechat/lang/pl.json
  src/Config/ModConfig.cs
  src/Gui/CustomElements/PlayerList.cs
  src/Gui/ModMenuDialog.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatServer.cs
  src/Utils/UIUtils.cs
Labels: enhancement

#88 Add German translations
  assets/rpvoicechat/lang/de.json
  modinfo.json
Labels: enhancement

#89 Fix mod not loading on the linux servers
  RPVoiceChat.csproj
  modinfo.json
  src/Audio/AudioData.cs
  src/Audio/Effects/EffectReverb.cs
  src/Audio/Effects/Filters/FilterLowpass.cs
  src/Audio/Input/IAudioCapture.cs
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Input/OpenALAudioCapture.cs
  src/Audio/OpenALCWrapper.cs
  src/Audio/OpenALWrapper.cs
  src/Audio/Output/CircularAudioBufer.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Audio/Output/PlayerListener.cs
  src/Networking/Packets/AudioPacket.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/Utils/AudioUtils.cs
  src/Utils/EmbeddedDllLoader.cs
Labels: bug, help wanted

#91 Add a command to toggle forceful rendering of name tags
  assets/rpvoicechat/lang/en.json
  src/Audio/Output/PlayerAudioSource.cs
  src/Blocks/BlockRegistry.cs
  src/Config/ModConfig.cs
  src/Config/WorldConfig.cs
  src/Gui/PlayerNameTagRenderer.cs
  src/Items/ItemRegistry.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/RPVoiceChatServer.cs
  src/Server/GameServer.cs
  src/Utils/Enums/ActivationMode.cs
  src/Utils/Enums/VoiceLevel.cs
Labels: enhancement

#94 Updated de.json
  assets/rpvoicechat/lang/de.json
Labels: enhancement

#95 Extend mod settings
  README.md
  assets/rpvoicechat/lang/en.json
  src/Audio/Input/MicrophoneManager.cs
  src/Config/RPVoiceChatConfig.cs
  src/Gui/CustomElements/AudioMeter.cs
  src/Gui/ModMenuDialog.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
Labels: bug, documentation, enhancement

#97 Downstream commits from net7
  .gitignore
  README.md
  assets/rpvoicechat/lang/de.json
  assets/rpvoicechat/lang/en.json
  assets/rpvoicechat/lang/ru.json
  modinfo.json
  src/Audio/Input/MicrophoneManager.cs
  src/Client/PlayerNetworkClient.cs
  src/Config/RPVoiceChatConfig.cs
  src/Gui/CustomElements/AudioMeter.cs
  src/Gui/ModMenuDialog.cs
  src/Networking/INetworkClient.cs
  src/Networking/INetworkServer.cs
  src/Networking/NativeNetwork/NativeNetworkBase.cs
  src/Networking/NativeNetwork/NativeNetworkServer.cs
  src/Networking/Packets/AudioPacket.cs
  src/Networking/Packets/ConnectionInfo.cs
  src/Networking/Packets/INetworkPacket.cs
  src/Networking/Packets/NetworkPacket.cs
  src/Networking/Packets/PacketType.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/Networking/UDPNetwork/UDPNetworkClient.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
  src/RPVoiceChatClient.cs
  src/Server/GameServer.cs
Labels: bug, documentation, enhancement

#96 Improve stability of the UDP transport
  src/Client/PlayerNetworkClient.cs
  src/Networking/INetworkClient.cs
  src/Networking/INetworkServer.cs
  src/Networking/NativeNetwork/NativeNetworkBase.cs
  src/Networking/NativeNetwork/NativeNetworkServer.cs
  src/Networking/Packets/AudioPacket.cs
  src/Networking/Packets/ConnectionInfo.cs
  src/Networking/Packets/INetworkPacket.cs
  src/Networking/Packets/NetworkPacket.cs
  src/Networking/Packets/PacketType.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/Networking/UDPNetwork/UDPNetworkClient.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
  src/RPVoiceChatClient.cs
  src/Server/GameServer.cs
Labels: bug, enhancement

#101 Refactor some old code to improve mod stability under heavy load
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/CircularAudioBufer.cs
  src/Client/PlayerNetworkClient.cs
  src/Config/ClientSettings.cs
  src/Config/ModConfig.cs
  src/Config/WorldConfig.cs
  src/Networking/INetworkServer.cs
  src/Networking/NativeNetwork/NativeNetworkClient.cs
  src/Networking/NativeNetwork/NativeNetworkServer.cs
  src/Networking/Packets/ConnectionInfo.cs
  src/Networking/Packets/NetworkPacket.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/Networking/UDPNetwork/UDPNetworkClient.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/RPVoiceChatServer.cs
  src/Server/GameServer.cs
  src/Utils/NetworkUtils.cs
Labels: bug, enhancement

#103 Downstream commits from net7
  Lib/OpenTK.Audio.OpenAL.dll
  Lib/OpenTK.Mathematics.dll
  assets/rpvoicechat/lang/de.json
  modinfo.json
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/CircularAudioBufer.cs
  src/Client/PlayerNetworkClient.cs
  src/Config/ClientSettings.cs
  src/Config/ModConfig.cs
  src/Config/WorldConfig.cs
  src/Networking/IExtendedNetworkClient.cs
  src/Networking/IExtendedNetworkServer.cs
  src/Networking/INetworkServer.cs
  src/Networking/NativeNetwork/NativeNetworkClient.cs
  src/Networking/NativeNetwork/NativeNetworkServer.cs
  src/Networking/Packets/ConnectionInfo.cs
  src/Networking/Packets/ConnectionRequest.cs
  src/Networking/Packets/NetworkPacket.cs
  src/Networking/Packets/PacketType.cs
  src/Networking/TCPNetwork/TCPConnection.cs
  src/Networking/TCPNetwork/TCPNetworkBase.cs
  src/Networking/TCPNetwork/TCPNetworkClient.cs
  src/Networking/TCPNetwork/TCPNetworkServer.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/Networking/UDPNetwork/UDPNetworkClient.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/RPVoiceChatServer.cs
  src/Server/GameServer.cs
  src/Utils/NetworkUtils.cs
Labels: bug, enhancement

#104 Fix packet ordering issues
  src/Audio/AudioData.cs
  src/Audio/Codecs/IAudioCodec.cs
  src/Audio/Codecs/OpusCodec.cs
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/AudioOutputManager.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Utils/Logger.cs
Labels: bug, enhancement

#105 Downstream commits from net7
  src/Audio/AudioData.cs
  src/Audio/Codecs/IAudioCodec.cs
  src/Audio/Codecs/OpusCodec.cs
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/AudioOutputManager.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Networking/Packets/AudioPacket.cs
  src/RPVoiceChatServer.cs
  src/Utils/Logger.cs
Labels: bug, enhancement

#106 Make audio encoding toggleable
  assets/rpvoicechat/lang/en.json
  src/Audio/AudioData.cs
  src/Audio/Codecs/DummyCodec.cs
  src/Audio/Codecs/IAudioCodec.cs
  src/Audio/Codecs/OpusCodec.cs
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/AudioOutputManager.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Networking/Packets/AudioPacket.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/RPVoiceChatServer.cs
  src/Utils/AudioUtils.cs
Labels: enhancement
