Repository Ridderrasmus/RPVoiceChat, pull requests merged in 2023-11, with the labels that each got.

#108 Various fixes and audio improvements
  README.md
  assets/rpvoicechat/lang/en.json
  modinfo.json
  src/Audio/Effects/Denoisers/RNNoiseDenoiser.cs
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/AudioOutputManager.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Audio/Output/PlayerListener.cs
  src/Client/PlayerNetworkClient.cs
  src/Config/ClientSettings.cs
  src/Config/ModConfig.cs
  src/Config/RPVoiceChatConfig.cs
  src/Config/WorldConfig.cs
  src/Gui/CustomElements/AudioMeter.cs
  src/Gui/Hud/SpeechIndicator.cs
  src/Gui/Hud/VoiceLevelIcon.cs
  src/Gui/ModMenuDialog.cs
  src/Networking/HealthCheckException.cs
  src/Networking/TCPNetwork/TCPConnection.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/Server/GameServer.cs
  src/Utils/AudioUtils.cs
  src/Utils/Logger.cs
  src/Utils/NoStackTraceException.cs
Labels: bug, documentation, enhancement

#111 Downstream commits from net7
  README.md
  modinfo.json
  src/Audio/Effects/Denoisers/RNNoiseDenoiser.cs
  src/Audio/Input/MicrophoneManager.cs
  src/Audio/Output/AudioOutputManager.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Audio/Output/PlayerListener.cs
  src/Client/PlayerNetworkClient.cs
  src/Config/ClientSettings.cs
  src/Config/ModConfig.cs
  src/Config/RPVoiceChatConfig.cs
  src/Config/WorldConfig.cs
  src/Gui/CustomElements/AudioMeter.cs
  src/Gui/Hud/SpeechIndicator.cs
  src/Gui/Hud/VoiceLevelIcon.cs
  src/Gui/ModMenuDialog.cs
  src/Networking/HealthCheckException.cs
  src/Networking/TCPNetwork/TCPConnection.cs
  src/Networking/TCPNetwork/TCPNetworkServer.cs
  src/Networking/UDPNetwork/UDPNetworkBase.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/Server/GameServer.cs
  src/Utils/AudioUtils.cs
  src/Utils/Logger.cs
  src/Utils/NoStackTraceException.cs
Labels: bug, documentation, enhancement

#110 Various improvements
  modinfo.json
  src/Audio/Effects/Denoisers/RNNoiseDenoiser.cs
  src/Audio/Output/AudioOutputManager.cs
  src/Audio/Output/PlayerAudioSource.cs
  src/Config/ClientSettings.cs
  src/Config/ModConfig.cs
  src/Config/RPVoiceChatConfig.cs
  src/Gui/ModMenuDialog.cs
  src/Networking/TCPNetwork/TCPConnection.cs
  src/Networking/TCPNetwork/TCPNetworkServer.cs
  src/Networking/UDPNetwork/UDPNetworkServer.cs
  src/RPVoiceChatClient.cs
  src/Utils/AudioUtils.cs
Labels: bug, enhancement

#112 Make NativeTCP unaffected by main thread lag
  README.md
  modinfo.json
  src/Audio/Output/PlayerAudioSource.cs
  src/Client/PlayerNetworkClient.cs
  src/Config/RPVoiceChatConfig.cs
  src/Networking/IExtendedNetworkServer.cs
  src/Networking/INetworkServer.cs
  src/Networking/NativeNetwork/NativeNetworkBase.cs
  src/Networking/NativeNetwork/NativeNetworkClient.cs
  src/Networking/NativeNetwork/NativeNetworkServer.cs
  src/Networking/NativeNetwork/ServerSystemNetworkProcess.cs
  src/Networking/TCPNetwork/TCPConnection.cs
  src/Patches/NetworkAPI.cs
  src/Patches/PatchManager.cs
  src/Patches/SystemNetworkProcess.cs
  src/Patches/TcpNetServer.cs
  src/RPVoiceChatClient.cs
  src/RPVoiceChatMod.cs
  src/RPVoiceChatServer.cs
  src/Server/GameServer.cs
Labels: documentation, enhancement

#117 Fix denoising artifacts at non-max strength
  Lib/OpenTK.Audio.OpenAL.dll
  Lib/OpenTK.Mathematics.dll
  RPVoiceChat.csproj
  src/Audio/Effects/Denoisers/RNNoiseDenoiser.cs
Labels: bug, enhancement

#118 Add audio configuration wizard
  assets/rpvoicechat/lang/en.json
  modinfo.json
  src/Audio/Input/MicrophoneManager.cs
  src/Config/ClientSettings.cs
  src/Gui/AudioWizardDialog.cs
  src/Gui/FirstLaunchDialog.cs
  src/Gui/GuiManager.cs
  src/Gui/ModMenuDialog.cs
  src/RPVoiceChatClient.cs
  src/Utils/AudioUtils.cs
Labels: enhancement

#119 Updated German translation
  assets/rpvoicechat/lang/de.json
Labels: enhancement

#120 Fix server crash caused by multi-threading
  modinfo.json
  src/Networking/NativeNetwork/ServerSystemNetworkProcess.cs
  src/Networking/TCPNetwork/TCPNetworkServer.cs
Labels: bug
